
makelist:
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	pha
	phy
	phx
	lda #79
	sta CursorX
	lda #59
	sta CursorY
	dec CursorX
	plx
	ply
	pla
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	nop
	rts		; Return to caller

